#!/usr/bin/env bash
# handle some signals and prints a string indefinitely
clean_up='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up" SIGQUIT

while [[ 1 -eq 1 ]]; do
	echo "To infinity and beyond"
done
