#!/usr/bin/env bash
# Installs HAProxy version 2.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 84106-web-01 54.144.155.41:80 check\n\tserver 84106-web-02 54.237.45.164:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
