#!/usr/bin/env bash
# this script prints "Best School" 10 times using while loop and prints "Hi" after the 9th iteration

count=0
while (( count<10 ))
do
	echo "Best School"
	if [ $count = 8 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
