#!/usr/bin/env bash
# this script prints "Best School" using while loop, prints "bad luck" on the 4th and "good luck" on the 8th iteration

count=0
while (( count<10 ))
do
	if [ $count = 3 ]
	then
		echo "bad luck"
	elif [ $count = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
