#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes using while loop
# displays hours from 0 to 12 and minutes from 1 to 59

hour=0
while (( hour<=12 ))
do
	echo "Hour: $hour"
	min=1
	while (( min<60 ))
	do
		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done
